apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-microservice
  template:
    metadata:
      labels:
        app: simple-microservice
    spec:
      containers:
      - name: simple-microservice
        image: eduardogama/simple-microservice
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
